version: "3.5"

services:

  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    container_name: digiclassroom_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data