// <auto-generated />
using System;
using DigiClassroom.Infrastructure.DBConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DigiClassroom.Infrastructure.Migrations
{
    [DbContext(typeof(DigiClassroomContext))]
    partial class DigiClassroomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ClassroomUser", b =>
                {
                    b.Property<Guid>("ClassroomsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassroomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserClassrooms");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssingnmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssingnmentId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Assingnment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Creation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Pontuation")
                        .HasPrecision(4, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Assingments");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LocationClassroom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssingnmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("AssingnmentId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.LibraryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LibraryFile");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryLibraryFile", b =>
                {
                    b.Property<Guid>("FilesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibrariesId")
                        .HasColumnType("uuid");

                    b.HasKey("FilesId", "LibrariesId");

                    b.HasIndex("LibrariesId");

                    b.ToTable("LibraryLibraryFiles");
                });

            modelBuilder.Entity("ClassroomUser", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiClassroom.Infrastructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Announcement", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.Classroom", null)
                        .WithMany("Announcements")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Answer", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.Assingnment", null)
                        .WithMany("Answers")
                        .HasForeignKey("AssingnmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Assingnment", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.Classroom", null)
                        .WithMany("Assingments")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Comment", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.Assingnment", null)
                        .WithMany("Comments")
                        .HasForeignKey("AssingnmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Library", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.Classroom", "Classroom")
                        .WithOne("Library")
                        .HasForeignKey("DigiClassroom.Infrastructure.Models.Library", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("LibraryLibraryFile", b =>
                {
                    b.HasOne("DigiClassroom.Infrastructure.Models.LibraryFile", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiClassroom.Infrastructure.Models.Library", null)
                        .WithMany()
                        .HasForeignKey("LibrariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Assingnment", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DigiClassroom.Infrastructure.Models.Classroom", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Assingments");

                    b.Navigation("Library");
                });
#pragma warning restore 612, 618
        }
    }
}
